### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by lrkwz** [BuBuaBu/gitlab-ci-lint#8]
After a fresh install

```
$ npm --version
4.1.2
$ npm install -g gitlab-ci-lint
/usr/local/bin/gitlab-ci-lint -> /usr/local/lib/node_modules/gitlab-ci-lint/bin/gitlab-ci-lint
/usr/local/lib
└─┬ gitlab-ci-lint@1.0.0 
  ├─┬ babbybel@1.0.0 
  │ └── node-hook@0.6.1 
  ├── commander@2.11.0 
  ├─┬ mz@2.6.0 
  │ ├── any-promise@1.3.0 
  │ ├── object-assign@4.1.1 
  │ └─┬ thenify-all@1.6.0 
  │   └── thenify@3.3.0 
  ├─┬ request@2.81.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.6.0 
  │ ├── caseless@0.12.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.1 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@2.1.4 
  │ │ └── asynckit@0.4.0 
  │ ├─┬ har-validator@4.2.1 
  │ │ ├─┬ ajv@4.11.8 
  │ │ │ └── co@4.6.0 
  │ │ └── har-schema@1.0.5 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.4.1 
  │ │ │ ├── assert-plus@1.0.0 
  │ │ │ ├── extsprintf@1.3.0 
  │ │ │ ├── json-schema@0.2.3 
  │ │ │ └─┬ verror@1.10.0 
  │ │ │   ├── assert-plus@1.0.0 
  │ │ │   └── core-util-is@1.0.2 
  │ │ └─┬ sshpk@1.13.1 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├── bcrypt-pbkdf@1.0.1 
  │ │   ├─┬ dashdash@1.14.1 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.7 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jsbn@0.1.1 
  │ │   └── tweetnacl@0.14.5 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.16 
  │ │ └── mime-db@1.29.0 
  │ ├── oauth-sign@0.8.2 
  │ ├── performance-now@0.2.0 
  │ ├── qs@6.4.0 
  │ ├── safe-buffer@5.1.1 
  │ ├── stringstream@0.0.5 
  │ ├─┬ tough-cookie@2.3.2 
  │ │ └── punycode@1.4.1 
  │ ├── tunnel-agent@0.6.0 
  │ └── uuid@3.1.0 
  ├─┬ request-promise@4.2.1 
  │ ├── bluebird@3.5.0 
  │ ├─┬ request-promise-core@1.1.1 
  │ │ └── lodash@4.17.4 
  │ └── stealthy-require@1.1.1 
  └─┬ standard@10.0.3 
    ├─┬ eslint@3.19.0 
    │ ├─┬ babel-code-frame@6.22.0 
    │ │ └── js-tokens@3.0.2 
    │ ├─┬ chalk@1.1.3 
    │ │ ├── ansi-styles@2.2.1 
    │ │ ├── escape-string-regexp@1.0.5 
    │ │ ├── has-ansi@2.0.0 
    │ │ ├── strip-ansi@3.0.1 
    │ │ └── supports-color@2.0.0 
    │ ├─┬ concat-stream@1.6.0 
    │ │ ├── inherits@2.0.3 
    │ │ ├─┬ readable-stream@2.3.3 
    │ │ │ ├── process-nextick-args@1.0.7 
    │ │ │ ├── string_decoder@1.0.3 
    │ │ │ └── util-deprecate@1.0.2 
    │ │ └── typedarray@0.0.6 
    │ ├─┬ debug@2.6.8 
    │ │ └── ms@2.0.0 
    │ ├─┬ doctrine@2.0.0 
    │ │ └── isarray@1.0.0 
    │ ├─┬ escope@3.6.0 
    │ │ ├─┬ es6-map@0.1.5 
    │ │ │ ├── d@1.0.0 
    │ │ │ ├── es5-ext@0.10.26 
    │ │ │ ├── es6-iterator@2.0.1 
    │ │ │ ├── es6-set@0.1.5 
    │ │ │ ├── es6-symbol@3.1.1 
    │ │ │ └── event-emitter@0.3.5 
    │ │ ├── es6-weak-map@2.0.2 
    │ │ └── esrecurse@4.2.0 
    │ ├─┬ espree@3.5.0 
    │ │ ├── acorn@5.1.1 
    │ │ └─┬ acorn-jsx@3.0.1 
    │ │   └── acorn@3.3.0 
    │ ├── esquery@1.0.0 
    │ ├── estraverse@4.2.0 
    │ ├── esutils@2.0.2 
    │ ├─┬ file-entry-cache@2.0.0 
    │ │ └─┬ flat-cache@1.2.2 
    │ │   ├── circular-json@0.3.3 
    │ │   ├─┬ del@2.2.2 
    │ │   │ ├─┬ globby@5.0.0 
    │ │   │ │ ├─┬ array-union@1.0.2 
    │ │   │ │ │ └── array-uniq@1.0.3 
    │ │   │ │ └── arrify@1.0.1 
    │ │   │ ├── is-path-cwd@1.0.0 
    │ │   │ ├─┬ is-path-in-cwd@1.0.0 
    │ │   │ │ └── is-path-inside@1.0.0 
    │ │   │ └── rimraf@2.6.1 
    │ │   ├── graceful-fs@4.1.11 
    │ │   └── write@0.2.1 
    │ ├─┬ glob@7.1.2 
    │ │ ├── fs.realpath@1.0.0 
    │ │ ├─┬ inflight@1.0.6 
    │ │ │ └── wrappy@1.0.2 
    │ │ ├── once@1.4.0 
    │ │ └── path-is-absolute@1.0.1 
    │ ├── globals@9.18.0 
    │ ├── ignore@3.3.3 
    │ ├── imurmurhash@0.1.4 
    │ ├─┬ inquirer@0.12.0 
    │ │ ├── ansi-escapes@1.4.0 
    │ │ ├── ansi-regex@2.1.1 
    │ │ ├─┬ cli-cursor@1.0.2 
    │ │ │ └─┬ restore-cursor@1.0.1 
    │ │ │   ├── exit-hook@1.1.1 
    │ │ │   └── onetime@1.1.0 
    │ │ ├── cli-width@2.1.0 
    │ │ ├── figures@1.7.0 
    │ │ ├─┬ readline2@1.0.1 
    │ │ │ ├── code-point-at@1.1.0 
    │ │ │ ├─┬ is-fullwidth-code-point@1.0.0 
    │ │ │ │ └── number-is-nan@1.0.1 
    │ │ │ └── mute-stream@0.0.5 
    │ │ ├── run-async@0.1.0 
    │ │ ├── rx-lite@3.1.2 
    │ │ ├── string-width@1.0.2 
    │ │ └── through@2.3.8 
    │ ├─┬ is-my-json-valid@2.16.0 
    │ │ ├── generate-function@2.0.0 
    │ │ ├─┬ generate-object-property@1.2.0 
    │ │ │ └── is-property@1.0.2 
    │ │ ├── jsonpointer@4.0.1 
    │ │ └── xtend@4.0.1 
    │ ├─┬ is-resolvable@1.0.0 
    │ │ └── tryit@1.0.3 
    │ ├─┬ js-yaml@3.9.1 
    │ │ ├─┬ argparse@1.0.9 
    │ │ │ └── sprintf-js@1.0.3 
    │ │ └── esprima@4.0.0 
    │ ├─┬ json-stable-stringify@1.0.1 
    │ │ └── jsonify@0.0.0 
    │ ├─┬ levn@0.3.0 
    │ │ ├── prelude-ls@1.1.2 
    │ │ └── type-check@0.3.2 
    │ ├─┬ mkdirp@0.5.1 
    │ │ └── minimist@0.0.8 
    │ ├── natural-compare@1.4.0 
    │ ├─┬ optionator@0.8.2 
    │ │ ├── deep-is@0.1.3 
    │ │ ├── fast-levenshtein@2.0.6 
    │ │ └── wordwrap@1.0.0 
    │ ├── path-is-inside@1.0.2 
    │ ├── pluralize@1.2.1 
    │ ├── progress@1.1.8 
    │ ├─┬ require-uncached@1.0.3 
    │ │ ├─┬ caller-path@0.1.0 
    │ │ │ └── callsites@0.2.0 
    │ │ └── resolve-from@1.0.1 
    │ ├─┬ shelljs@0.7.8 
    │ │ ├── interpret@1.0.3 
    │ │ └── rechoir@0.6.2 
    │ ├── strip-bom@3.0.0 
    │ ├── strip-json-comments@2.0.1 
    │ ├─┬ table@3.8.3 
    │ │ ├── ajv-keywords@1.5.1 
    │ │ ├── slice-ansi@0.0.4 
    │ │ └─┬ string-width@2.1.1 
    │ │   ├── is-fullwidth-code-point@2.0.0 
    │ │   └─┬ strip-ansi@4.0.0 
    │ │     └── ansi-regex@3.0.0 
    │ ├── text-table@0.2.0 
    │ └─┬ user-home@2.0.0 
    │   └── os-homedir@1.0.2 
    ├── eslint-config-standard@10.2.1 
    ├── eslint-config-standard-jsx@4.0.2 
    ├─┬ eslint-plugin-import@2.2.0 
    │ ├── builtin-modules@1.1.1 
    │ ├── contains-path@0.1.0 
    │ ├── doctrine@1.5.0 
    │ ├── eslint-import-resolver-node@0.2.3 
    │ ├─┬ eslint-module-utils@2.1.1 
    │ │ └── pkg-dir@1.0.0 
    │ ├─┬ has@1.0.1 
    │ │ └── function-bind@1.1.0 
    │ ├── lodash.cond@4.5.2 
    │ ├─┬ minimatch@3.0.4 
    │ │ └─┬ brace-expansion@1.1.8 
    │ │   ├── balanced-match@1.0.0 
    │ │   └── concat-map@0.0.1 
    │ └─┬ pkg-up@1.0.0 
    │   └─┬ find-up@1.1.2 
    │     ├── path-exists@2.1.0 
    │     └─┬ pinkie-promise@2.0.1 
    │       └── pinkie@2.0.4 
    ├─┬ eslint-plugin-node@4.2.3 
    │ ├─┬ resolve@1.4.0 
    │ │ └── path-parse@1.0.5 
    │ └── semver@5.3.0 
    ├── eslint-plugin-promise@3.5.0 
    ├─┬ eslint-plugin-react@6.10.3 
    │ ├─┬ array.prototype.find@2.0.4 
    │ │ ├─┬ define-properties@1.1.2 
    │ │ │ └── foreach@2.0.5 
    │ │ └─┬ es-abstract@1.8.0 
    │ │   ├─┬ es-to-primitive@1.1.1 
    │ │   │ ├── is-date-object@1.0.1 
    │ │   │ └── is-symbol@1.0.1 
    │ │   ├── is-callable@1.1.3 
    │ │   └── is-regex@1.0.4 
    │ ├── doctrine@1.5.0 
    │ ├── jsx-ast-utils@1.4.1 
    │ └─┬ object.assign@4.0.4 
    │   └── object-keys@1.0.11 
    ├── eslint-plugin-standard@3.0.1 
    └─┬ standard-engine@7.0.0 
      ├─┬ deglob@2.1.0 
      │ ├── find-root@1.1.0 
      │ ├─┬ pkg-config@1.1.1 
      │ │ └── debug-log@1.0.1 
      │ ├── run-parallel@1.1.6 
      │ └── uniq@1.0.1 
      ├── get-stdin@5.0.1 
      ├── minimist@1.2.0 
      └─┬ pkg-conf@2.0.0 
        ├─┬ find-up@2.1.0 
        │ └─┬ locate-path@2.0.0 
        │   ├─┬ p-locate@2.0.0 
        │   │ └── p-limit@1.1.0 
        │   └── path-exists@3.0.0 
        └─┬ load-json-file@2.0.0 
          ├─┬ parse-json@2.2.0 
          │ └─┬ error-ex@1.3.1 
          │   └── is-arrayish@0.2.1 
          └── pify@2.3.0 
```

```shell
$ gitlab-ci-lint
/usr/local/lib/node_modules/gitlab-ci-lint/node_modules/babbybel/index.js:47
      let outline = line
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitlab-ci-lint/bin/gitlab-ci-lint:3:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by BuBuaBu** [comment]
This "let " syntax is supported by node since version 6.0.0
I will fix this issue, node 4.x is still under maintenance. Until then you can use Node 6.x :)
